### ISSUE TITLE
函数防抖以及节流

### ISSUE THREAD

**Issue by xdandsl** [YvetteLau/Step-By-Step#11]
函数防抖：n秒内只执行一次函数，如果n秒以内重新触发函数，则重新计时n秒去执行函数。使用场景：搜索时，等用户输入完几秒钟才去发送请求
函数节流：n秒内只执行一次，如果n秒内重新触发函数，不执行,等到n秒时触发再去执行。

1,防抖示例：
const timer = null;
function fangDou(){
    clearTimeout(timer) //清除上一次的定时器
    timer = setTimeout(() => {
        console.log(1)
    },3000)
}
2,节流示例:
const time = 0;
function jiuLIu(){
    if(time -5000 < 0){ //5秒内再触发直接return不予执行
        return
    }
    console.log(123)
    time = new Date()
}

**Comment by YvetteLau** [comment]
> 函数防抖：n秒内只执行一次函数，如果n秒以内重新触发函数，则重新计时n秒去执行函数。使用场景：搜索时，等用户输入完几秒钟才去发送请求
> 函数节流：n秒内只执行一次，如果n秒内重新触发函数，不执行,等到n秒时触发再去执行。
> 
> 1,防抖示例：
> const timer = null;
> function fangDou(){
> clearTimeout(timer) //清除上一次的定时器
> timer = setTimeout(() => {
> console.log(1)
> },3000)
> }
> 2,节流示例:
> const time = 0;
> function jiuLIu(){
> if(time -5000 < 0){ //5秒内再触发直接return不予执行
> return
> }
> console.log(123)
> time = new Date()
> }

issue我关掉了~~~
下次在已有的issue下回答哈~
