### ISSUE TITLE
看到后才去了解的

### ISSUE THREAD

**Issue by Cain-kz** [YvetteLau/Step-By-Step#13]
函数节流 和 函数防抖 ：
两者核心：使用setTimeout 和 clearTimeout 限制一个方法被频繁的触发。已达到减少请求的次数，减少服务器的压力。

参考上面的 https://www.jianshu.com/p/091c5fb96112  写了一遍
/*函数节流(throttle)*/
function throttle(fn,interval = 300){  
  let canRun = true;
  return function(){
    if(!canRun) return;
    canRun = false;
    setTimeout(()=>{
      fn.apply(this,arguments);
      canRun = true;
    },interval)
  }
}
/*函数防抖(debounce)*/
function debounce(fn,interval = 300){
  let timeout =null;
  return function() {
    clearTimeout(timeout) // 清除时间
    timeout = setInterval(()=>{
      fn.apply(this,arguments);
    },interval);
  }
}

**Comment by kaiking01** [comment]
他们主要区别在哪里？

**Comment by KRISACHAN** [comment]
别新开issue吖

**Comment by YvetteLau** [comment]
> 函数节流 和 函数防抖 ：
> 两者核心：使用setTimeout 和 clearTimeout 限制一个方法被频繁的触发。已达到减少请求的次数，减少服务器的压力。
> 
> 参考上面的 https://www.jianshu.com/p/091c5fb96112 写了一遍
> /_函数节流(throttle)_/
> function throttle(fn,interval = 300){
> let canRun = true;
> return function(){
> if(!canRun) return;
> canRun = false;
> setTimeout(()=>{
> fn.apply(this,arguments);
> canRun = true;
> },interval)
> }
> }
> /_函数防抖(debounce)_/
> function debounce(fn,interval = 300){
> let timeout =null;
> return function() {
> clearTimeout(timeout) // 清除时间
> timeout = setInterval(()=>{
> fn.apply(this,arguments);
> },interval);
> }
> }

不要新开issue~
