### ISSUE TITLE
Yuko

### ISSUE THREAD

**Issue by Yuko7245** [YvetteLau/Step-By-Step#22]
事件代理就是在祖先级DOM元素绑定一个事件，当触发子孙级DOM元素的事件时，利用事件流的原理来触发绑定在祖先级DOM的事件

**Comment by YvetteLau** [comment]
> 事件代理就是在祖先级DOM元素绑定一个事件，当触发子孙级DOM元素的事件时，利用事件流的原理来触发绑定在祖先级DOM的事件

在对应的issue下回答，不要新建issue~
